kafka:
  brokerAddress: localhost:9092
  topic: employee
spring:
  datasource:
    url: jdbc:h2:mem:employeedb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
  kafka:
    producer:
      properties:
        spring.json.add.type.header: false
  h2:
    console:
      enabled:  true
      path: /console